spring:
  datasource:
    url: jdbc:mysql://${db.host}/${db.schema}
    username: ${db.user}
    password: ${db.password}

  sql:
    init:
      mode: always

  jpa:
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  secret: ${jwt.secret}

json:
  roles: /json/roles.json
  categories: /json/categories.json