spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: always

  jpa:
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  secret: ${JWT_SECRET}

json:
  roles: /json/roles.json
  categories: /json/categories.json

