spring:
  datasource:
    url: jdbc:mysql://localhost/flashcards
    username: root
    password: 27111995

  sql:
    init:
      mode: always

  jpa:
    show-sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  secret: fdAFEAEFafSDFK32940JDSF234F22Rf2Ff2FakoEOKenR342nOSF90564KFD2093